apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullName }}-{{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fullName }}-{{ .Values.service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.fullName }}-{{ .Values.service.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args: ["--sep-server"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-configmap