apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  tls:
    - hosts:
      - www.stellaranchordemo.com
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: www.stellaranchordemo.com
    http:
      paths:
      - path: /info
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /.well-known/stellar.toml
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /auth
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep6
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep12
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080      
      - path: /sep24
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep31
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /sep38
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080
      - path: /customer
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8080