apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort }}       # port number the service will listen on
    targetPort: {{ .Values.service.targetPort }}  # port number pods listen on
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}