#RBAC and service account
{{- if .Values.serviceAccount  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- if (.Values.serviceAccount).annotations }}
  annotations:
    annotations:
    {{- with .Values.serviceAccount.annotations }}
{{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- if .Values.rbac }}
apiVersion: v1
kind: List
items:
  #define the rights
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: {{ .Release.Name }}-role
      namespace: {{ .Release.Namespace }}
      {{- if (.Values.rbac).annotations }}
      annotations:
        {{- with .Values.rbac.annotations }}
{{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    rules:
{{ toYaml .Values.rbac.rules | indent 6 }} 
  #link the Role to the namespace
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: {{ .Release.Name }}-bind
      namespace: {{ .Release.Namespace }}
    subjects:
      - kind: ServiceAccount
        name: {{ .Values.serviceAccount.name }}
        namespace: {{ .Release.Namespace }}
    roleRef:
      kind: Role
      name: {{ .Release.Name }}-role
      apiGroup: rbac.authorization.k8s.io
{{- end }}