version: 0.2
env:
  variables:
    environment: "dev"
  secrets-manager:
    DOCKER_LOGIN_PW: "/CodeBuild/dockerLoginPassword"     
phases:
  build:
    commands:
      - docker login -u reecemarkowsky -p $DOCKER_LOGIN_PW
      - cd docs/resources/deployment-examples/aws-fargate-ecs
      - go get github.com/b-b3rn4rd/json2ssm
      - aws s3 cp s3://anchorplatformhelmchart/anchor-config.yaml .
      - cat ./anchor-config.yaml
      - docker build . -t anchor-config
      - docker tag anchor-platform reecemarkowsky/anchor-config:latest
      - docker push reecemarkowsky/anchor-config:latest
