version: 0.2
env:
  variables:
    environment: "$ANCHOR_CONFIG_ENVIRONMENT"
  secrets-manager:
    DOCKER_LOGIN_PW: "$ANCHOR_CONFIG_DOCKER_LOGIN_SECRET"     
phases:
  build:
    commands:
      - cd docs/resources/deployment-examples/aws-fargate-ecs
      - aws s3 cp $ANCHOR_CONFIG_S3_BUCKET/anchor_config.yaml .
      - aws s3 cp $ANCHOR_CONFIG_S3_BUCKET/stellar.toml ./stellar_wks.toml
      - aws s3 cp $ANCHOR_CONFIG_S3_BUCKET/reference_config.yaml .
      - mkdir /config
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ANCHOR_CONFIG_ECR_REPO
      - docker build . -t anchor-config
      - docker tag anchor-config $ANCHOR_CONFIG_S3_BUCKET:latest
      - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$ANCHOR_CONFIG_ECR_REPO:latest $ANCHOR_CONFIG_S3_BUCKET:latest