apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: anchor-platform
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080       # port number the service will listen on
    targetPort: 8080 # port number pods listen on
  selector:
    app: sep